### PR TITLE
Add poem test to reproduce an issue

### PR DESCRIPTION
**Pull request by fperie**
Hello,

it's a new pull request to demonstrate the issue described in the issue #29 
Can you look this problem ?

With this patch, the project compilation don't pass the tests.

Thank's a lot,
Fabien

### CODE REVIEW

**Comment by fperie** [comment]
I tried and got the same behavior with vertx dependencies in version 3.4.2
This issue is not recent.
Very strange ...
An idea of the problem ?

**Comment by fperie** [comment]
Hello pmlopes,

this PR follows a request from Julien Viet in the #29 who wants to have a PR to reproduce the problem.
So, it's normal that the build project fails

Fabien

**Comment by vietj** [comment]
yes check this for 3.6.0 it might require a change in vertx deployer

**Comment by fperie** [comment]
This problem seems old, it was already present in versions 3.4.2, 3.5.4 and 3.6.0-SNAPSHOT.

**Comment by fperie** [comment]
If you want, I can test a patch to validate the fix.
Unfortunately, I don't know enough the vertx core to propose a fix

**Comment by vietj** [comment]
can you paste the stack trace here ?

**Comment by fperie** [comment]
Running io.vertx.ext.sync.poem.TestVertxSync
starting on the beforeAll() method...

```
[quasar] ERROR: Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextInternal;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization
        at co.paralleluniverse.fibers.instrument.InstrumentMethod.dumpCodeBlock(InstrumentMethod.java:720)
        at co.paralleluniverse.fibers.instrument.InstrumentMethod.accept(InstrumentMethod.java:415)
        at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:265)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:120)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
        at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:187)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:473)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:126)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:652)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:627)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:593)
        at io.vertx.ext.sync.poem.TestVertxSync.beforeAll(TestVertxSync.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:95)
        at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
        at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
        at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
        at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
        at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
        at io.vertx.ext.unit.junit.VertxUnitRunner$3.evaluate(VertxUnitRunner.java:211)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[quasar] ERROR: while transforming io/vertx/core/impl/DeploymentManager$DeploymentImpl: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextInternal;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextInternal;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization
        at co.paralleluniverse.fibers.instrument.InstrumentMethod.dumpCodeBlock(InstrumentMethod.java:720)
        at co.paralleluniverse.fibers.instrument.InstrumentMethod.accept(InstrumentMethod.java:415)
        at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:265)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:120)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
        at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:187)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:473)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:126)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:652)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:627)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:593)
        at io.vertx.ext.sync.poem.TestVertxSync.beforeAll(TestVertxSync.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:95)
        at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
        at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:90)
        at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
        at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
        at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:194)
        at io.vertx.ext.unit.junit.VertxUnitRunner$3.evaluate(VertxUnitRunner.java:211)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
QUASAR WARNING: Assertions enabled. This may harm performance.
deploy PoemVerticleForTesting verticle    [ OK ]
unit test 'testLoadTheDormeurDuValPoem' in running...
starting on the afterAll() method...
undeploiement PoemVerticleForTesting verticle    [ OK ]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.202 sec <<< FAILURE! - in io.vertx.ext.sync.poem.TestVertxSync
testLoadTheDormeurDuValPoem(io.vertx.ext.sync.poem.TestVertxSync)  Time elapsed: 0.047 sec  <<< ERROR!
io.vertx.core.VertxException: java.lang.IllegalThreadStateException: Method called not from within a fiber
        at co.paralleluniverse.fibers.FiberAsync.requestSync(FiberAsync.java:289)
        at co.paralleluniverse.fibers.FiberAsync.runSync(FiberAsync.java:255)
        at co.paralleluniverse.fibers.FiberAsync.run(FiberAsync.java:111)
        at io.vertx.ext.sync.Sync.awaitResult(Sync.java:48)
        at io.vertx.ext.sync.poem.TestVertxSync.testLoadTheDormeurDuValPoem(TestVertxSync.java:89)
```

**Comment by vietj** [comment]
it seems that this method fails to be instrumented:

```
    private synchronized void rollback(ContextInternal callingContext, Handler<AsyncResult<String>> completionHandler, ContextImpl context, Throwable cause) {
      if (status == ST_DEPLOYED) {
        status = ST_UNDEPLOYING;
        doUndeployChildren(callingContext, childrenResult -> {
          synchronized (DeploymentImpl.this) {
            status = ST_UNDEPLOYED;
          }
          if (childrenResult.failed()) {
            reportFailure(cause, callingContext, completionHandler);
          } else {
            context.runCloseHooks(closeHookAsyncResult -> reportFailure(cause, callingContext, completionHandler));
          }
        });
      }
    }
```

due to the synchronisation, I would try to have instead:

```
    private void rollback(ContextInternal callingContext, Handler<AsyncResult<String>> completionHandler, ContextImpl context, Throwable cause) {
      synchronized (this) {
        if (status != ST_DEPLOYED) {
          return;
        }
        status = ST_UNDEPLOYING;
      }
      doUndeployChildren(callingContext, childrenResult -> {
        synchronized (DeploymentImpl.this) {
          status = ST_UNDEPLOYED;
        }
        if (childrenResult.failed()) {
          reportFailure(cause, callingContext, completionHandler);
        } else {
          context.runCloseHooks(closeHookAsyncResult -> reportFailure(cause, callingContext, completionHandler));
        }
      });
    }
```

can you try to patch vertx core with this and see if that fixes the issue ?

**Comment by fperie** [comment]
Hello Julien,

I tried your solution in copying/pasting the DeploymentManager class in my project in the same io.vertx.core.impl package.
Sadly, the fix doesn't seem to work in my case.


ERROR[m] Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl
[1;31mco.paralleluniverse.fibers.instrument.UnableToInstrumentException[m: [1;31mUnable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextInternal;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization[m
    [1mat[m co.paralleluniverse.fibers.instrument.InstrumentMethod.dumpCodeBlock ([1mInstrumentMethod.java:720[m)
    [1mat[m co.paralleluniverse.fibers.instrument.InstrumentMethod.accept ([1mInstrumentMethod.java:415[m)
    [1mat[m co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd ([1mInstrumentClass.java:265[m)
    [1mat[m co.paralleluniverse.asm.ClassReader.accept ([1mUnknown Source[m)
    [1mat[m co.paralleluniverse.asm.ClassReader.accept ([1mUnknown Source[m)
    [1mat[m co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass ([1mQuasarInstrumentor.java:120[m)
    [1mat[m co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass ([1mQuasarInstrumentor.java:92[m)
    [1mat[m com.vlkan.maven.plugins.quasar.QuasarInstrumentorMojo.instrumentClass ([1mQuasarInstrumentorMojo.java:158[m)
    [1mat[m com.vlkan.maven.plugins.quasar.QuasarInstrumentorMojo.instrumentClasses ([1mQuasarInstrumentorMojo.java:149[m)
    [1mat[m com.vlkan.maven.plugins.quasar.QuasarInstrumentorMojo.execute ([1mQuasarInstrumentorMojo.java:127[m)
    [1mat[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo ([1mDefaultBuildPluginManager.java:134[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:208[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:154[m)
    [1mat[m org.apache.maven.lifecycle.internal.MojoExecutor.execute ([1mMojoExecutor.java:146[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:117[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject ([1mLifecycleModuleBuilder.java:81[m)
    [1mat[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build ([1mSingleThreadedBuilder.java:51[m)
    [1mat[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute ([1mLifecycleStarter.java:128[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:309[m)
    [1mat[m org.apache.maven.DefaultMaven.doExecute ([1mDefaultMaven.java:194[m)
    [1mat[m org.apache.maven.DefaultMaven.execute ([1mDefaultMaven.java:107[m)
    [1mat[m org.apache.maven.cli.MavenCli.execute ([1mMavenCli.java:955[m)
    [1mat[m org.apache.maven.cli.MavenCli.doMain ([1mMavenCli.java:290[m)
    [1mat[m org.apache.maven.cli.MavenCli.main ([1mMavenCli.java:194[m)
    [1mat[m sun.reflect.NativeMethodAccessorImpl.invoke0 ([1mNative Method[m)
    [1mat[m sun.reflect.NativeMethodAccessorImpl.invoke ([1mNativeMethodAccessorImpl.java:62[m)
    [1mat[m sun.reflect.DelegatingMethodAccessorImpl.invoke ([1mDelegatingMethodAccessorImpl.java:43[m)
    [1mat[m java.lang.reflect.Method.invoke ([1mMethod.java:498[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced ([1mLauncher.java:289[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.launch ([1mLauncher.java:229[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode ([1mLauncher.java:415[m)
    [1mat[m org.codehaus.plexus.classworlds.launcher.Launcher.main ([1mLauncher.java:356[m)
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time: 12.051 s
[[1;34mINFO[m] Finished at: 2018-11-01T08:53:03+01:00
[[1;34mINFO[m] Final Memory: 31M/206M
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32mcom.vlkan:quasar-maven-plugin:0.7.3:instrument[m [1m(default)[m on project [36mvertx-sync[m: [1;31mExecution default of goal com.vlkan:quasar-maven-plugin:0.7.3:instrument failed: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextInternal;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization[m -> [1m[Help 1][m

**Comment by vietj** [comment]
@jponge can you investigate this issue using the reproducer ?

**Comment by jponge** [comment]
I'll have a look, but it may be deferred to Monday, I have important deadlines to meet on the book _now_ 😉

**Comment by vietj** [comment]
sure thing

**Comment by vietj** [comment]
book first

**Comment by fperie** [comment]
hello @jponge,
this is a breaking news ?
What is the book title ? In english ? In french ?

Fabien

**Comment by vietj** [comment]
best recent news :-) https://www.manning.com/books/vertx-in-action

**Comment by jponge** [comment]
I can indeed reproduce these warnings in tests, looking more into it.

**Comment by jponge** [comment]
So the error here is that non-fiber / non-Vert.x-managed thread code is being called, and Quasar eventually complains that a suspendable method is being run from a regular thread.

I got the test to pass by wrapping the test (which runs from a JUnit thread) into a fiber:

```java
  @Test
  public void testLoadTheDormeurDuValPoem(TestContext context) throws Exception {
    new Fiber<Void>(() -> {
      LOGGER.info("unit test 'testLoadTheDormeurDuValPoem' in running...");
      try {
        final String poem = Sync.awaitResult(h -> VERTICLE.loadTheDormeurDuValPoem());
        assertThat(poem).isNotEmpty().contains("Rimbaud");
      } catch (Exception e) {
        context.fail(e);
      }
    }).start();
  }
```


Please let me know if I am missing anything here.

**Comment by jponge** [comment]
(note: it doesn't look like a bug to me)

**Comment by fperie** [comment]
Hello @jponge,
Thank tout for your answer.
At least, this issue should be explained in the documentation, no ?

**Comment by fperie** [comment]
I test this work around ASAP
Fabien

**Comment by jponge** [comment]
> At least, this issue should be explained in the documentation, no ?

Absolutely!

**Comment by fperie** [comment]
Hum on your solution, i think that the fiber doesn't wait for the end of assertions to complete the test method, no ??

Then, how to do if the verticle needs sync in starting step (via @Before method)?

**Comment by jponge** [comment]
Whoops, you’re right

**Comment by jponge** [comment]
I have something ugly but that works here. It adheres to the model of _"a verticle always interacts with the outside world using the event-bus"_.

In your verticle, add an event bus listener:

```java
@Override
  public void start() throws Exception {
    vertx.eventBus().consumer("dormeur", m -> {
      try {
        m.reply(new Fiber<>(this::loadTheDormeurDuValPoem).start().get());
      } catch (ExecutionException | InterruptedException e) {
        e.printStackTrace();
      }
    });
  }
```

It spins a new fiber for replying.

Now this test works:

```java
  @Test
  public void testMessaging(TestContext context) {
    Async async = context.async();
    vertx.eventBus().send("dormeur", new JsonObject(), context.asyncAssertSuccess(r -> {
      String text = (String) r.body();
      assertThat(text)
        .isNotNull()
        .isNotEmpty()
        .contains("Rimbaud");
      async.complete();
    }));
  }
```

Note: I have built a version of `vertx-core` with no `synchronize` instructions in `DeploymentManagerImpl#rollback`. It removes all warnings, but they are not the cause of the issues, just annoyances.

**Comment by jponge** [comment]
My guess is that basically when on the event-loop, you are not necessarily on a fiber.

**Comment by fperie** [comment]
Should not the vertx-sync project offer a solution for using vertx-sync in Junit 4/5?

**Comment by fperie** [comment]
In fact, I would like also to use the sync instruction in a proxy service. 
Can i do it ?
This issue has been tagged 3.6.0.  
What should be the release date ?

Thank's a lot,
Fabien

**Comment by vietj** [comment]
we're aiming a CR this week, we still have a couple of things to address before final.

**Comment by jponge** [comment]
What we need to better document is that calling fiber code from non-fibers is a problem, and that creating fibers may be required in some places.

On proxy services: the async bits can use fibers in their implementations, this is orthogonal to proxies.

**Comment by jponge** [comment]
@fperie Here is a cleaner version by interacting with a `FiberScheduler` of a `SyncVerticle`:

```java
  @Override
  public void start() throws Exception {
    vertx.eventBus().consumer("dormeur", m -> {
      instanceScheduler.newFiber(() -> {
        m.reply(loadTheDormeurDuValPoem());
        return null;
      }).start();
    });
  }
```

**Comment by jponge** [comment]
(or use can use `newStrand`)

**Comment by fperie** [comment]
Hello @jponge (and @vietj),

the cleaner version by interacting with a FiberScheduler of a SyncVerticle works very well.
Finally, in verticles that use SyncVerticle, you must have only private methods that use Sync.awaitResult() called from a message.

On the other hand, I don't understand you must return null in start method :

  ```
@Override
  public void start() throws Exception {
    vertx.eventBus().consumer("dormeur", m -> {
      instanceScheduler.newFiber(() -> {
        m.reply(loadTheDormeurDuValPoem());
        return null;
      }).start();
    });
  }
```
  
Another thing, I don't understand the last comment : (or use can use newStrand) ??
What do you mean ?


Then, if I look the source code of the SyncVerticle class, I don't understant why, in the start method with a future in parameter,
you call startFuture.complete(); just after SyncVerticle.this.start(); then that the start() method can use asynchronous callback, no ?

```
@Override
public void start(Future<Void> startFuture) throws Exception {
	instanceScheduler = Sync.getContextScheduler();
	new Fiber<Void>(instanceScheduler, () -> {
	  try {
		SyncVerticle.this.start();
		startFuture.complete();
	  } catch (Throwable t) {
		startFuture.fail(t);
	  }
	}).start();
}
```

Thank's a lot,
Fabien

**Comment by jponge** [comment]
> On the other hand, I don't understand you must return null in start method :

Because a fiber is a `Fiber<T>`, so it must have a return value no matter what.

> Another thing, I don't understand the last comment : (or use can use newStrand) ??
> What do you mean ?

A strand is an abstraction of a fiber or thread, see https://docs.paralleluniverse.co/quasar/javadoc/co/paralleluniverse/strands/Strand.html

> 
> Then, if I look the source code of the SyncVerticle class, I don't understant why, in the start method with a future in parameter,
> you call startFuture.complete(); just after SyncVerticle.this.start(); then that the start() method can use asynchronous callback, no ?
> 
> @Override
> public void start(Future<Void> startFuture) throws Exception {
> 	instanceScheduler = Sync.getContextScheduler();
> 	new Fiber<Void>(instanceScheduler, () -> {
> 	  try {
> 		SyncVerticle.this.start();
> 		startFuture.complete();
> 	  } catch (Throwable t) {
> 		startFuture.fail(t);
> 	  }
> 	}).start();
> }

It’s to wrap the start code into a fiber, and bridge with the Vert.x future that signals the successful or erroneous deployment of the verticle.

**Comment by fperie** [comment]
Hello @jponge,

excuse me, I still don't understand why we didn't write the following code:

```
	@Override
	public void start(Future<Void> startFuture) throws Exception {
		instanceScheduler = Sync.getContextScheduler();
		new Fiber<Void>(instanceScheduler, () -> {
		  try {
			SyncVerticle.this.start();
			return null;
		  } catch (Throwable t) {
			startFuture.fail(t);
		  }
		}).start().get();
		startFuture.complete();
	}
```
	
In the previous implementation, the fiber can't be terminated when the startFuture.complete(); instruction will be called.
I drool or I didn't understand ?

Thank's a lot,
Fabien

**Comment by jponge** [comment]
No, when you spin the fiber it lives its life without blocking the start method.

**Comment by jponge** [comment]
Actually I forgot about `fiberHandler` which does exactly what I did with creating a fiber:

```java
    vertx.eventBus().consumer("dormeur", Sync.fiberHandler(m -> m.reply(loadTheDormeurDuValPoem())));
```

**Pull request closed without merging**
