### PR TITLE
Upgraded to Quasar 0.7.9

### PR DESCRIPTION
**Pull request by GordonMcKinney**

### CODE REVIEW

**Comment by vietj** [comment]
can you list the quasar dependencies that changes such as Guava, etc... ?

**Comment by GordonMcKinney** [comment]
Here's an abridged diff of the two files, focusing on version changes:
```
23c25
<     version             = "0.7.5"
---
>     version             = "0.7.9"
41,42c43,44
<     ext.asmVer    = '5.1'
<     ext.kotlinVer = '1.0.1-2'
---
>     ext.asmVer    = '5.2'
>     ext.kotlinVer = '1.1.3-2'. **** KOTLIN VERSION CHANGED
102c104
<         compile("io.dropwizard.metrics:metrics-core:3.1.2") {
---
>         compile("io.dropwizard.metrics:metrics-core:3.2.3") {
105,106c107,108
<         provided "org.apache.ant:ant:1.9.7"
<         compile "com.google.guava:guava:19.0"
---
>         provided "org.apache.ant:ant:1.9.9" // version 1.10 and upwards requires JDK 8
>         compile "com.google.guava:guava:20.0" // version 21.0 and upwards requires JDK 8
110c112
<         testCompile('com.google.truth:truth:0.28') {
---
>         testCompile('com.google.truth:truth:0.34') {
120,121c122,123
<         jmhCompile 'org.openjdk.jmh:jmh-core:1.12'
<         jmhCompile 'org.openjdk.jmh:jmh-generator-annprocess:1.12'
---
>         jmhCompile 'org.openjdk.jmh:jmh-core:1.19'
>         jmhCompile 'org.openjdk.jmh:jmh-generator-annprocess:1.19'
161a167
>         if (project.name != 'quasar-kotlin') { // TODO investigate why kotlin-plugin 1.1.2+ doesn't like it
165a172
>         }
437c453
<         compile "org.hdrhistogram:HdrHistogram:2.1.8"
---
>         compile "org.hdrhistogram:HdrHistogram:2.1.9"
447c463
<         compile("com.esotericsoftware:kryo:3.0.3") {
---
>         compile("com.esotericsoftware:kryo:4.0.0") {
450c466
<         compile("de.javakaffee:kryo-serializers:0.37") {
---
>         compile("de.javakaffee:kryo-serializers:0.42") {
611,613c628,630
<         compile "org.slf4j:slf4j-api:1.7.21"
<         compile "net.bytebuddy:byte-buddy:1.3.19"
<         testRuntime("org.apache.logging.log4j:log4j-slf4j-impl:2.5") {
---
>         compile "org.slf4j:slf4j-api:1.7.25"
>         compile "net.bytebuddy:byte-buddy:1.7.1"
>         testRuntime("org.apache.logging.log4j:log4j-slf4j-impl:2.8.2") {
616,618c633,635
<         testRuntime "org.apache.logging.log4j:log4j-api:2.5"
<         testRuntime "org.apache.logging.log4j:log4j-core:2.5"
<         testRuntime "com.lmax:disruptor:3.3.4" // required for log4j
---
>         testRuntime "org.apache.logging.log4j:log4j-api:2.8.2"
>         testRuntime "org.apache.logging.log4j:log4j-core:2.8.2"
>         testRuntime "com.lmax:disruptor:3.3.6" // required for log4j
682c699
<         testCompile('org.testng:testng:6.9.10') {
---
>         testCompile('org.testng:testng:6.12') {
698c715
<         compile "com.lmax:disruptor:3.3.4"
---
>         compile "com.lmax:disruptor:3.3.6"
```

**Comment by doctorpangloss** [comment]
Just a note that my fork of `vertx-sync` has been using 0.7.9 for a while now with vertx 3.5.1 and everything works fine.

**Comment by vietj** [comment]
can you provide a more digest / synthetic report of the dependency changes ?

**Comment by fperie** [comment]
Hello @vietj, @doctorpangloss and @GordonMcKinney 

In my project, I get a NullPointerException if I call successively twice Sync.awaitResullt...
This issue is known and resolved from the 0.7.8-20170117.084120-3 version of quasar-core (cf. [https://github.com/puniverse/quasar/issues/236](https://github.com/puniverse/quasar/issues/236))

But if I force the last 0.7.x version of quasar-core (0.7.10) and quasar maven plugin (0.7.9), I get the following stack trace:

`**[quasar] ERROR: Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl
java.lang.NullPointerException**

        at co.paralleluniverse.asm.MethodWriter.visitMaxs(Unknown Source)
        at co.paralleluniverse.asm.tree.MethodNode.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:260)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:134)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:94)
        at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:209)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:476)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:126)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:658)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:633)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:599)`

With the 0.8.0 version of quasar-core, the jdk8 classifier has disappeared.

**Comment by jponge** [comment]
Yes, it has to be a more involving upgrade.

Last time that I checked, Quasar also had been compiled with JDK 9+, so it is a problem with Vert.x that has JDK 8 compatibility for now.

**Comment by fperie** [comment]
Hello @vietj, @doctorpangloss and @GordonMcKinney, 

The last version of quasar-core compatible with JDK8 is the 0.7.10 with the classifier jdk8 :

```
<dependency>
     <groupId>co.paralleluniverse</groupId>
     <artifactId>quasar-core</artifactId>
     <version>0.7.10</version>
     <classifier>jdk8</classifier>
</dependency>
```

As of version 0.8.0 (latest version), the library is only compatible with [jdk9 ... jdk11]

Between version 0.7.3 and 0.7.10, many bugs have been fixed:
 * [https://github.com/puniverse/quasar/releases/tag/v0.7.4](https://github.com/puniverse/quasar/releases/tag/v0.7.4)
 * [https://github.com/puniverse/quasar/releases/tag/v0.7.5](https://github.com/puniverse/quasar/releases/tag/v0.7.5)
 * [https://github.com/puniverse/quasar/releases/tag/v0.7.6](https://github.com/puniverse/quasar/releases/tag/v0.7.6)
 * [https://github.com/puniverse/quasar/releases/tag/v0.7.7](https://github.com/puniverse/quasar/releases/tag/v0.7.7)
 * [https://github.com/puniverse/quasar/releases/tag/v0.7.8](https://github.com/puniverse/quasar/releases/tag/v0.7.8)
 * [https://github.com/puniverse/quasar/releases/tag/v0.7.9](https://github.com/puniverse/quasar/releases/tag/v0.7.9)
 * [https://github.com/puniverse/quasar/releases/tag/v0.7.10](https://github.com/puniverse/quasar/releases/tag/v0.7.10)

For example, my NPE issue has been fixed in version 0.7.9
Unfortunately, the latest version 0.7.x of quasar-core is not compatible with vertx 3.6.0-SNAPSHOT
sniff

**Comment by vietj** [comment]
@fperie what is not compatible ?

**Comment by jponge** [comment]
@vietj I remember you had concerns with Guava / etc, right?

**Comment by vietj** [comment]
can we force the version to the current one used by the project ?

**Comment by fperie** [comment]
Hello @vietj, @doctorpangloss and @GordonMcKinney,

I have no problem with guava, vertx-sync has just a dependency on guava in version 20.0 (maven scope compile).

In my project, with following dependencies :
  - quasar-core: 0.7.5-jdk8
  - quasar-maven-plugin: 0.7.3


In my project, all units tests passed with the following code used in junit5 method annoted with @BeforeAll :
```

VERTICLE = new AbstractW2Verticle() 
{
	@Override
	protected void onStarting(final Future<Void> onStartingFuture) 
	{
		try
		{
			final StringBuilder result = new StringBuilder();
			final FileSystem fileSystem = vertx.fileSystem();
			
			File f = new File("./target/test-classes/le_dormeur_du_val.txt");
			LOGGER.info("positionnement du fichier : " + f.getAbsolutePath());
			
			final boolean exists = Sync.awaitResult(h -> fileSystem.exists("./target/test-classes/le_dormeur_du_val.txt", h));
			
			if (!exists)
			{
				LOGGER.warn("le fichier ./target/test-classes/le_dormeur_du_val.txt est inexistant");
				onStartingFuture.fail(new FileNotFoundException("fichier ./target/test-classes/le_dormeur_du_val.txt introuvable"));
			}
			else
			{
				vertx.fileSystem().readFile("./target/test-classes/le_dormeur_du_val.txt", new Handler<AsyncResult<Buffer>>() 
				{
					@Override
					public void handle(final AsyncResult<Buffer> loadPoemEvent) 
					{
						if (loadPoemEvent.succeeded())
						{
							final Buffer buf = loadPoemEvent.result();
							result.append( (buf == null) ? "" : buf.toString() );
						}
						
						final String poem = result.toString();
						
						testContext.verify(() -> { 
							assertThat(poem).isNotEmpty();
							assertThat(poem).as("le poeme doit contenir le mot Rimbaud").contains("Rimbaud");
						});
						
						onStartingFuture.complete();
					}
				});
			}
		}
		catch (VertxException ve)
		{
			onStartingFuture.fail(ve);
		}
	}
};
```



The same project in forcing the following dependencies :
  - quasar-core: 0.7.10-jdk8
  - quasar-maven-plugin: 0.7.3
  
```
[ERROR] Failed to execute goal com.vlkan:quasar-maven-plugin:0.7.3:instrument (default) on project w2-vertx-core: Execution default of goal com.vlkan:quasar-maven-plugin:0.7.3:instrument failed: An API incompatibility was encountered while executing com.vlkan:quasar-maven-plugin:0.7.3:instrument: java.lang.NoSuchMethodError: co.paralleluniverse.fibers.instrument.QuasarInstrumentor.<init>(ZLjava/lang/ClassLoader;Lco/paralleluniverse/fibers/instrument/SuspendableClassifier;)V
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.vlkan:quasar-maven-plugin:0.7.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/c:/pgih/repository/com/vlkan/quasar-maven-plugin/0.7.3/quasar-maven-plugin-0.7.3.jar
[ERROR] urls[1] = file:/c:/pgih/repository/co/paralleluniverse/quasar-core/0.7.10/quasar-core-0.7.10-jdk8.jar
[ERROR] urls[2] = file:/c:/pgih/repository/io/dropwizard/metrics/metrics-core/3.2.3/metrics-core-3.2.3.jar
[ERROR] urls[3] = file:/c:/pgih/repository/com/google/guava/guava/20.0/guava-20.0.jar
[ERROR] urls[4] = file:/c:/pgih/repository/org/hdrhistogram/HdrHistogram/2.1.9/HdrHistogram-2.1.9.jar
[ERROR] urls[5] = file:/c:/pgih/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar
[ERROR] urls[6] = file:/c:/pgih/repository/com/esotericsoftware/kryo/4.0.0/kryo-4.0.0.jar
[ERROR] urls[7] = file:/c:/pgih/repository/com/esotericsoftware/reflectasm/1.11.3/reflectasm-1.11.3.jar
[ERROR] urls[8] = file:/c:/pgih/repository/com/esotericsoftware/minlog/1.3.0/minlog-1.3.0.jar
[ERROR] urls[9] = file:/c:/pgih/repository/org/objenesis/objenesis/2.2/objenesis-2.2.jar
[ERROR] urls[10] = file:/c:/pgih/repository/de/javakaffee/kryo-serializers/0.42/kryo-serializers-0.42.jar
[ERROR] urls[11] = file:/c:/pgih/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[12] = file:/c:/pgih/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[13] = file:/c:/pgih/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[14] = file:/c:/pgih/repository/javax/inject/javax.inject/1/javax.inject-1.jar
[ERROR] urls[15] = file:/c:/pgih/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0/org.eclipse.sisu.inject-0.3.0.jar
[ERROR] urls[16] = file:/c:/pgih/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[17] = file:/c:/pgih/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.3/maven-plugin-annotations-3.3.jar
[ERROR] urls[18] = file:/c:/pgih/repository/co/paralleluniverse/quasar-core/0.7.3/quasar-core-0.7.3.jar
[ERROR] urls[19] = file:/c:/pgih/repository/com/lmax/disruptor/3.3.2/disruptor-3.3.2.jar
[ERROR] urls[20] = file:/c:/pgih/repository/com/esotericsoftware/kryo/kryo/2.24.0/kryo-2.24.0.jar
[ERROR] urls[21] = file:/c:/pgih/repository/com/esotericsoftware/minlog/minlog/1.2/minlog-1.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>fr.xxxxxx.xxxx:xxxxxx:0.3-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
```



The same project in forcing the following dependencies :
  - quasar-core: 0.7.10-jdk8
  - quasar-maven-plugin: 0.7.9
  
```
[quasar] ERROR: while transforming io/vertx/core/impl/DeploymentManager$DeploymentImpl: null
java.lang.NullPointerException
        at co.paralleluniverse.asm.MethodWriter.visitMaxs(Unknown Source)
        at co.paralleluniverse.asm.tree.MethodNode.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:260)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:134)
        at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:94)
        at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:209)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:476)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:126)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:658)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:633)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:599)
        at fr.xxxxxxx.xx.xxxxx.xxxxx.AbstractW2VerticleTest.beforeAll(AbstractW2VerticleTest.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllMethods$8(ClassTestDescriptor.java:373)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllMethods(ClassTestDescriptor.java:372)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:201)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:74)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:102)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by vietj** [comment]
there is quasar 0.8.0 that has been released I ca nsee

**Comment by jponge** [comment]
Quasar 0.8.0 is not JDK 8 compatible

**Comment by fperie** [comment]
@jponge, @vietj 
Yes, but Quasar 0.7.10 with jdk8 classifier is compatible to java 8

**Comment by jponge** [comment]
See #31

**Comment by vietj** [comment]
I'm for any update that remains compatible with the current Guava version of the stack.

That being said, we can have a Maven profile that tests with another set of Quasar version and document it + having this profile executed in Travis ?

WDYT ?

**Comment by jponge** [comment]
> I'm for any update that remains compatible with the current Guava version of the stack.

What version is it?

> That being said, we can have a Maven profile that tests with another set of Quasar version and document it + having this profile executed in Travis ?

This will break, 0.7.10 is the last JDK8 one anyway.

**Comment by jponge** [comment]
@vietj @fperie #31 is fine to merge I think

**Comment by jponge** [comment]
Fixed by #31

**Pull request closed without merging**
